version: "3.7"

services:
  qferp:
    #找到当前目录下的java文件夹构建
    build: ./
    #镜像名称
    image: qferp:latest
    container_name: qferp810
    restart: always
    environment:
       TZ: Asia/Shanghai
       web.port: 810
       db.host: 172.16.159.136
       db.port: 3306
       db.name: xh-oa
       redis.host: 172.16.159.136
       redis.password: xhhw123
    volumes:
      - /home/qferp/upfiles:/upfiles
      - /home/qferp/logs:/deploy/logs
    ports:
      - "810:810"
    networks:
      - xh-net

networks:
  xh-net:
    external: false
